### PR TITLE
Semicolon bug

### PR DESCRIPTION
**Pull request by andyg7**
Just got rid of unnecessary semicolon. Also edited DepthFirstSearch.java - should we not do stack.removeFirst() on line 170? I've added more detail on the actual commit (https://github.com/andyg7/hipster/commit/dde3cf3b793a4c9dd4b3abb4a7e71f3703b8e72e)

### CODE REVIEW

**Comment by pablormier** [comment]
It seems that you're right. Could you please add that graph example as a test? Many thanks!

**Comment by andyg7** [comment]
Just pushed that test - created a new file UndirectedGraphSearchExample.java in hipster-examples where I implement the DFS search.

**Comment by pablormier** [comment]
Thanks!

**Comment by andyg7** [comment]
:)

**Pull request merged**
